config/routes.rb
IssueTracker::Application.routes.draw do
  resources :issues
  root :to => 'sessions#new'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id, :user
  belongs_to :user
  validates :provider, :uid, :presence => true
#  validates_uniqueness_of :uid, :scope => :provider

  def self.find_or_create(auth_hash)
   unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    user = User.create( :nickname => auth_hash["info"]["nickname"])
    auth = create :user =>user , :provider => auth_hash["provider"], :uid => auth_hash["uid"]
   end
   auth
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :description, :priority, :subject
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :nickname
  has_many :authorizations
  has_many :issues
  validates :nickname, :presence => true

  def add_provider(auth_hash)
  # Check if the provider already exists, so we don't add it twice
   unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index

#    @issues = Issue.all
unless session[:user_id]
  redirect_to root_url
  return
end
# Get all issues related to user where the primary key of User record is in session[:user_id]
    @issues = User.find(session[:user_id]).issues

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
# Create a new issue given the primary key of User record is in session[:user_id]

    @issue = Issue.new
    @issue.user_id= session[:user_id]


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
# Create a new issue given the primary key of User record is in session[:user_id]
    @issue = Issue.new(params[:issue])
    @issue.user_id= session[:user_id]

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
#    render :text => request.env['omniauth.auth'].inspect
    auth_hash = request.env['omniauth.auth']
    $name=auth_hash["info"]["nickname"]
    $provider=auth_hash["provider"]
#    render :text => "<pre>"+request.env["omniauth.auth"].to_yaml+"</pre>"


#   Logout user to force authorisation every time app is run
    session[:user_id] = nil


    if session[:user_id]
      # Means our user is signed in. Add the authorization to the user
      User.find(session[:user_id]).add_provider(auth_hash)

#      render :text => "You are already authorized and logged in through #{auth_hash["provider"].capitalize} "
    else
      # Log him in or sign him up
      auth = Authorization.find_or_create(auth_hash)

      # Create the session
      session[:user_id] = auth.user.id

#      render :text => "Welcome #{auth.user.nickname} , you are authorized and logged in through #{auth_hash["provider"].capitalize} "
#      render :text => "<pre>"+auth_hash.to_yaml+"</pre>"
    end
#    $name=auth.user.nickname
#    flash[:notice]= "Welcome #{auth.user.nickname} , you are authorized and logged in through #{auth_hash["provider"].capitalize}"

    redirect_to :controller =>'issues'
  end

  def destroy
    session[:user_id] = nil
    render :text => "You've logged out!"
  end

  def failure
    render :text => "Sorry, but you didn't allow access to our app!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h1><%=if $name
         $name.capitalize
       end
        %> Issues List</h1>

<h3>Logged in through <%=if $provider
         $provider.capitalize end %></h3>

<table>
  <tr>
    <th>Subject</th>
    <th>Priority</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= issue.subject %></td>
    <td><%= issue.priority %></td>
    <td><%= issue.description %></td>
    <td><%= link_to 'Show', issue %></td>
    <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
    <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @issue.subject %>
</p>

<p>
  <b>Priority:</b>
  <%= @issue.priority %>
</p>

<p>
  <b>Description:</b>
  <%= @issue.description %>
</p>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IssueTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>